Headache with Selenium

diff --git a/.github/workflows/rubyonrails.yml b/.github/workflows/rubyonrails.yml
--- a/.github/workflows/rubyonrails.yml
+++ b/.github/workflows/rubyonrails.yml
@@ -30,11 +30,31 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-      # Add or replace dependency steps here
+
       - name: Install Ruby and gems
         uses: ruby/setup-ruby@v1
         with:
           bundler-cache: true
+      - name: Setup chromedriver
+        uses: nanasess/setup-chromedriver@master
+        with:
+          # Optional: do not specify to match Chrome's version
+          chromedriver-version: "100.0.4896.20"
+
+      - name: Debug Chrome Path
+        run: |
+          echo "Checking common chrome paths..."
+          ls -l /usr/local/bin/google-chrome || echo "Not found in /usr/local/bin/google-chrome"
+          ls -l /usr/bin/google-chrome || echo "Not found in /usr/bin/google-chrome"
+          ls -l /opt/google/chrome/google-chrome || echo "Not found in /opt/google/chrome/google-chrome"
+          which chrome || echo "Chrome binary not found in PATH"
+      - name: Add Chrome to PATH
+        run: echo "/usr/bin" >> $GITHUB_PATH
+      - run: |
+          export DISPLAY=:99
+          chromedriver --url-base=/wd/hub &
+          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
+
       # Add or replace database setup steps here
       #- name: Set up database schema
       #  run: bin/rails db:schema:load
